import type { Product } from "@/types/product";

const placeholderImage = "/products/placeholder.jpg";

// Placeholder catalog data until BEDIFF product content and assets are added.
export const products: Product[] = [
  {
    id: "bediff-split-short",
    slug: "bediff-split-short",
    name: "BEDIFF SPLIT SHORT",
    price: 2499,
    colors: ["Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [placeholderImage],
    category: "Shorts",
  },
  {
    id: "bediff-running-vest",
    slug: "bediff-running-vest",
    name: "BEDIFF RUNNING VEST",
    price: 1999,
    colors: ["Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [placeholderImage],
    category: "Tops",
  },
  {
    id: "bediff-air-short",
    slug: "bediff-air-short",
    name: "BEDIFF AIR SHORT",
    price: 2299,
    colors: ["Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [placeholderImage],
    category: "Shorts",
  },
  {
    id: "bediff-race-short",
    slug: "bediff-race-short",
    name: "BEDIFF RACE SHORT",
    price: 2799,
    colors: ["Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [placeholderImage],
    category: "Shorts",
  },
  {
    id: "bediff-performance-tee",
    slug: "bediff-performance-tee",
    name: "BEDIFF PERFORMANCE TEE",
    price: 2199,
    colors: ["Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [placeholderImage],
    category: "Tops",
  },
  {
    id: "bediff-mesh-top",
    slug: "bediff-mesh-top",
    name: "BEDIFF MESH TOP",
    price: 1899,
    colors: ["Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [placeholderImage],
    category: "Tops",
  },
  {
    id: "bediff-training-pant",
    slug: "bediff-training-pant",
    name: "BEDIFF TRAINING PANT",
    price: 3499,
    colors: ["Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [placeholderImage],
    category: "Pants",
  },
  {
    id: "bediff-performance-hoodie",
    slug: "bediff-performance-hoodie",
    name: "BEDIFF PERFORMANCE HOODIE",
    price: 4499,
    colors: ["Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [placeholderImage],
    category: "Outerwear",
  },
];
